<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StudentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('students')->insert([
            [
                'full_name' => 'Andi Pratama',
                'school_id' => '123456789',
                'national_school_id' => '987654321',
                'nickname' => 'Andi',
                'class' => '5A',
                'place_of_birth' => 'Jakarta',
                'date_of_birth' => Carbon::create('2010', '04', '15'),
                'gender' => 'male',
                'religion' => 'Islam',
                'nationality' => 'Indonesian',
                'address' => 'Jl. Merdeka No. 123, Jakarta',
                'city' => 'Jakarta',
                'postal_code' => '10110',
                'living_with' => 'Father and Mother',
                'has_siblings_at_school' => true,
                'previous_school_name' => 'SD Harapan Bangsa',
                'previous_school_class' => '4B',
                'previous_school_address' => 'Jl. Pendidikan No. 45, Jakarta',
                'previous_school_phone' => '021-1234567',
                'father_name' => 'Budi Pratama',
                'father_email' => 'budi@example.com',
                'father_phone' => '081234567890',
                'father_nationality' => 'Indonesian',
                'father_id_card_number' => '3501234567890001',
                'father_kitas_number' => null,
                'father_job' => 'Engineer',
                'father_company' => 'PT. ABC',
                'father_position' => 'Senior Engineer',
                'father_office_phone' => '021-5678901',
                'father_office_address' => 'Jl. Industri No. 10, Jakarta',
                'father_monthly_income' => 15000000.00,
                'mother_name' => 'Siti Aisyah',
                'mother_email' => 'siti@example.com',
                'mother_phone' => '082345678901',
                'mother_nationality' => 'Indonesian',
                'mother_id_card_number' => '3509876543210002',
                'mother_kitas_number' => null,
                'mother_job' => 'Teacher',
                'mother_company' => 'SMP Negeri 1',
                'mother_position' => 'Mathematics Teacher',
                'mother_office_phone' => '021-2345678',
                'mother_office_address' => 'Jl. Pendidikan No. 5, Jakarta',
                'mother_monthly_income' => 8000000.00,
                'guardian_name' => null,
                'guardian_email' => null,
                'guardian_phone' => null,
                'guardian_nationality' => null,
                'guardian_id_card_number' => null,
                'guardian_kitas_number' => null,
                'guardian_job' => null,
                'guardian_company' => null,
                'guardian_position' => null,
                'guardian_office_phone' => null,
                'guardian_office_address' => null,
                'guardian_monthly_income' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Rina Sari',
                'school_id' => '987654321',
                'national_school_id' => '123456789',
                'nickname' => 'Rina',
                'class' => '4B',
                'place_of_birth' => 'Surabaya',
                'date_of_birth' => Carbon::create('2011', '06', '30'),
                'gender' => 'female',
                'religion' => 'Christianity',
                'nationality' => 'Indonesian',
                'address' => 'Jl. Raya No. 456, Surabaya',
                'city' => 'Surabaya',
                'postal_code' => '60123',
                'living_with' => 'Mother',
                'has_siblings_at_school' => false,
                'previous_school_name' => 'SD Pahlawan',
                'previous_school_class' => '3A',
                'previous_school_address' => 'Jl. Pahlawan No. 12, Surabaya',
                'previous_school_phone' => '031-2345678',
                'father_name' => 'Krisna Sari',
                'father_email' => 'krisna@example.com',
                'father_phone' => '081234567891',
                'father_nationality' => 'Indonesian',
                'father_id_card_number' => '3509876543210003',
                'father_kitas_number' => null,
                'father_job' => 'Doctor',
                'father_company' => 'RSUD Surabaya',
                'father_position' => 'Surgeon',
                'father_office_phone' => '031-9876543',
                'father_office_address' => 'Jl. Kesehatan No. 2, Surabaya',
                'father_monthly_income' => 20000000.00,
                'mother_name' => 'Dewi Lestari',
                'mother_email' => 'dewi@example.com',
                'mother_phone' => '082345678902',
                'mother_nationality' => 'Indonesian',
                'mother_id_card_number' => '3501234567890004',
                'mother_kitas_number' => null,
                'mother_job' => 'Nurse',
                'mother_company' => 'RSUD Surabaya',
                'mother_position' => 'Senior Nurse',
                'mother_office_phone' => '031-8765432',
                'mother_office_address' => 'Jl. Kesehatan No. 2, Surabaya',
                'mother_monthly_income' => 10000000.00,
                'guardian_name' => null,
                'guardian_email' => null,
                'guardian_phone' => null,
                'guardian_nationality' => null,
                'guardian_id_card_number' => null,
                'guardian_kitas_number' => null,
                'guardian_job' => null,
                'guardian_company' => null,
                'guardian_position' => null,
                'guardian_office_phone' => null,
                'guardian_office_address' => null,
                'guardian_monthly_income' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
